# Generated by Django 4.2.7 on 2026-03-30 18:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('rol', models.CharField(choices=[('ota', 'Ota'), ('ona', 'Ona'), ('farzand', 'Farzand'), ('boshqa', 'Boshqa')], default='boshqa', max_length=10)),
                ('avatar_emoji', models.CharField(default='👤', max_length=10)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HaftalikTaomnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaratilgan_sana', models.DateField(default=django.utils.timezone.now)),
                ('taomnoma_json', models.JSONField(verbose_name="Taomnoma ma'lumotlari")),
                ('daraja', models.CharField(max_length=10, verbose_name='Daraja')),
                ('mahsulotlar_royxati', models.TextField(verbose_name='Ishlatilgan mahsulotlar')),
                ('faol', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Haftalik Taomnoma',
                'verbose_name_plural': 'Haftalik Taomnomalar',
                'ordering': ['-yaratilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='KunlikTaom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=12)),
                ('taom_nomi', models.CharField(max_length=200)),
                ('retsept', models.TextField(verbose_name='Retsept')),
                ('ingredientlar', models.JSONField(verbose_name="Ingredientlar ro'yxati")),
                ('tayyorlash_vaqti', models.PositiveIntegerField(default=30, verbose_name='Tayyorlash vaqti (daqiqa)')),
                ('qiyinlik', models.CharField(choices=[('oson', 'Oson'), ('ortacha', "O'rtacha"), ('qiyin', 'Qiyin')], default='ortacha', max_length=10)),
                ('galaba_qozondi', models.BooleanField(default=False)),
                ('taomnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunlik_taomlar', to='api.haftaliktaomnoma')),
            ],
            options={
                'verbose_name': 'Kunlik Taom',
                'verbose_name_plural': 'Kunlik Taomlar',
            },
        ),
        migrations.CreateModel(
            name='Oila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Oila nomi')),
                ('kod', models.CharField(max_length=8, unique=True, verbose_name="Qo'shilish kodi")),
                ('daraja', models.CharField(choices=[('tejamkor', 'Tejamkor (Byudjetli)'), ('ortacha', "O'rtacha (Standart)"), ('tokin', "To'kin-sochin (Premium)")], default='ortacha', max_length=10, verbose_name='Byudjet darajasi')),
                ('oylik_byudjet', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Oylik byudjet (so'm)")),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('yaratuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yaratgan_oila', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oila',
                'verbose_name_plural': 'Oilalar',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Miqdor')),
                ('birlik', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litr'), ('ml', 'Millilitr'), ('dona', 'Dona'), ('boshqalar', 'Boshqalar')], default='kg', max_length=10)),
                ('narx', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="Narx (so'm)")),
                ('qoshilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('oila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='api.oila')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.AddField(
            model_name='haftaliktaomnoma',
            name='oila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taomnomalar', to='api.oila'),
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='oila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='azolar', to='api.oila'),
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Ovoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovozlar', to=settings.AUTH_USER_MODEL)),
                ('taom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ovozlar', to='api.kunliktaom')),
            ],
            options={
                'verbose_name': 'Ovoz',
                'verbose_name_plural': 'Ovozlar',
                'unique_together': {('foydalanuvchi', 'taom')},
            },
        ),
    ]
